# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: kbyte.io
google_analytics: kbyte.io
title: Christian Fibich

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: kbyte.io

description: Christian Fibich
author:
  name: Christian Fibich
  bio: Electronics Enthusiast, Hacker, Retro Hardware Freak, History Nerd, Runner, Urban Explorer
  workplace: FH Technikum Wien

  professional:
    github: cfib
    bitbucket: cfibich
    email: fibich@technikum-wien.at
    uni: http://embsys.technikum-wien.at

  private:
    bitbucket: cfib90
    email: christian.fibich+kbyteio@gmail.com
    twitter: _stderr
    linkedin: cfibich
    email_md5: 8c4897ea4cea56991966ce562f2b505b

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:

